language: java
jdk:
  - oraclejdk8
notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change
install:
- mvn -version -B
script:
- mvn -s .travis.maven.settings.xml verify | grep -vF "[INFO] Downloading:" | grep
  -vF "[INFO] Downloaded:"; test ${PIPESTATUS[0]} -eq 0
env:
  global:
    - secure: "iulQmX6ImXmXDUK0XKTlnjB8/vVekiZzif7EYOXU3f8wGMxm/DQ/WIsX5hhrgMfkPLrAGblkZVR1tQEpw19fj7/xtWsyW2qWjDZxsLm++zalSyDXBy6CAIEK4980xsvx0/7tnIxz9eqqyD4bKSeQwEJ72Ab1LMBPDOOvHjZaGlw="
    - secure: "D6p9aHSP4Lzhe8CKfjNiD3sMatOEuK36LoFPd52A97NFkFSw3N1cqF0Crkz4uSHyBuunxS/c9aejoDmNowRgJ5x7g/Eg5f+tFZdxLwYHeZwMIxxSUiDODGo+kEEhL90l1rqTnzNqxynWcaXazIkNe+RvL+fiJyVlj9i72irMGmo="
after_success:
- test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" && mvn  -s .travis.maven.settings.xml deploy -DskipTests
